(library 
  (name client)
  (preprocess 
    (pps ppx_blob))
  (preprocessor_deps
    (file ../../assets/fonts/Roboto-Bold.ttf)
    (file ../../assets/fonts/Roboto-Regular.ttf)
    (file ../../assets/pieces/Chess_bdt60.png)
    (file ../../assets/pieces/Chess_blt60.png)
    (file ../../assets/pieces/Chess_kdt60.png)
    (file ../../assets/pieces/Chess_klt60.png)
    (file ../../assets/pieces/Chess_ndt60.png)
    (file ../../assets/pieces/Chess_nlt60.png)
    (file ../../assets/pieces/Chess_pdt60.png)
    (file ../../assets/pieces/Chess_plt60.png)
    (file ../../assets/pieces/Chess_qdt60.png)
    (file ../../assets/pieces/Chess_qlt60.png)
    (file ../../assets/pieces/Chess_rdt60.png)
    (file ../../assets/pieces/Chess_rlt60.png))
  (libraries core raylib game))
